"""empty message

Revision ID: ece4777d5fd5
Revises: 01b6331e17e6
Create Date: 2023-09-19 15:10:40.744038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ece4777d5fd5'
down_revision = '01b6331e17e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state',
    sa.Column('state_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_table('lga',
    sa.Column('lga_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('lga_name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['state.state_id'], ),
    sa.PrimaryKeyConstraint('lga_id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('admin_pwd',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('admin_pwd',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    op.drop_table('lga')
    op.drop_table('state')
    # ### end Alembic commands ###
